# Generated by Django 5.2.17 on 2026-09-08 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('status', models.CharField(choices=[('available', "Bo'sh"), ('occupied', 'Band'), ('reserved', 'Rezerv'), ('maintenance', 'Nosoz')], default='available', max_length=20, verbose_name='Holat')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kompyuter',
                'verbose_name_plural': 'Kompyuterlar',
                'ordering': ['room', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism familiya')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('category', models.CharField(choices=[('electricity', 'Elektr'), ('internet', 'Internet'), ('repair', "Ta'mirlash"), ('salary', 'Ish haqi'), ('rent', 'Ijara'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Kategoriya')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Xona nomi')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Raqam')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('hourly_price', models.DecimalField(decimal_places=2, default=10000, max_digits=12, verbose_name='Soatlik narx')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='Cyber Club', max_length=200, verbose_name='Klub nomi')),
                ('currency', models.CharField(default='UZS', max_length=20, verbose_name='Valyuta')),
                ('default_hourly_price', models.DecimalField(decimal_places=2, default=10000, max_digits=12, verbose_name='Standart soatlik narx')),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Kechikish uchun qo'shimcha to'lov")),
                ('dark_mode', models.BooleanField(default=True, verbose_name='Dark mode')),
                ('auto_refresh_interval', models.IntegerField(default=15, verbose_name='Avto yangilash (sekund)')),
                ('default_calculation_method', models.CharField(choices=[('hourly', 'Soatlik (real vaqt)'), ('per_minute', 'Har daqiqada'), ('fixed', 'Belgilangan muddat')], default='hourly', max_length=20, verbose_name='Standart hisoblash usuli')),
                ('notification_minutes_before_end', models.IntegerField(default=10, verbose_name='Tugashga necha daqiqa qolganda ogohlantirish')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sozlama',
                'verbose_name_plural': 'Sozlamalar',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish')),
                ('end_time', models.DateTimeField(verbose_name='Tugash')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('completed', 'Tugagan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.computer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.room')),
            ],
            options={
                'verbose_name': 'Rezervatsiya',
                'verbose_name_plural': 'Rezervatsiyalar',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='core.room'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish')),
                ('planned_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Rejalashtirilgan tugash')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Amalda tugash')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Vaqt (daqiqa)')),
                ('calculation_method', models.CharField(choices=[('hourly', 'Soatlik (real vaqt)'), ('per_minute', 'Har daqiqada'), ('fixed', 'Belgilangan muddat')], default='hourly', max_length=20, verbose_name='Hisoblash usuli')),
                ('hourly_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Soatlik narx')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami narx')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan")),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Tugagan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name='Holat')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.computer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.room')),
            ],
            options={
                'verbose_name': 'Sessiya',
                'verbose_name_plural': 'Sessiyalar',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('click', 'Click'), ('payme', 'Payme'), ('uzcard', 'UzCard'), ('humo', 'Humo')], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.session')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='computer',
            unique_together={('room', 'name')},
        ),
    ]
