# Generated by Django 5.2.17 on 2026-09-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='computer',
            index=models.Index(fields=['status'], name='core_comput_status_464204_idx'),
        ),
        migrations.AddIndex(
            model_name='computer',
            index=models.Index(fields=['room', 'status'], name='core_comput_room_id_973c81_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_at'], name='core_expens_created_c79526_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='core_expens_categor_358de0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['session', 'created_at'], name='core_paymen_session_60c715_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='core_reserv_status_3b8861_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['computer', 'status'], name='core_reserv_compute_7118d6_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='core_sessio_status_45f1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['start_time'], name='core_sessio_start_t_c4b042_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['computer', 'status'], name='core_sessio_compute_1e6f48_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['customer'], name='core_sessio_custome_e9f01f_idx'),
        ),
    ]
