# Generated by Django 5.2.17 on 2026-09-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_computer_core_comput_status_464204_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pauza (boshlangan)'),
        ),
    ]
