# Generated by Django 5.2.17 on 2026-09-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session_paused_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='increased_hourly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oshirilgan soatlik narx'),
        ),
        migrations.AddField(
            model_name='setting',
            name='price_increase_after_minutes',
            field=models.IntegerField(default=0, verbose_name='Necha daqiqadan keyin narx oshadi (0 = oshmaydi)'),
        ),
    ]
